### ISSUE TITLE
Saluton. Mia estas DMCA Takedown kontrolilo por minecraft

### ISSUE THREAD

**Issue by dmcacheckerforminecraft** [XCRailway/XCRailAdvancedReplacer#1]
Ŝajnis esti vi havas iun Minecraft projekto dosieron en GitHub.
Ŝajnis esti via politiko estas limigita en Minecraft Server politiko.
Bonvolu certigi vin ne auxskultos la Minecraft Server regulo, aŭ ni la organizo povas sendi DMCA takedown peto konfirmi via Repos.

Dankon pro via kompreno.
DMCA Takedown Kontrolilo por Minecraft Project.

Aug 6, 2016

**Comment by XCRailway** [comment]
什么意思？

**Comment by dmcacheckerforminecraft** [comment]
Um.. Sorry, let me translate this request.

Your policy on your Minecraft seemed to be obey to the Minecraft Server Eula.
Please check your writings, or we will send a DMCA Takedown request to Github.
Thanks for your understanding

**Comment by XCRailway** [comment]
Can you translate it to Chinese?

**Comment by dmcacheckerforminecraft** [comment]
We have no Chinese knowledge so I use Google Translate to translate it.
你對你的 Minecraft 政策似乎违反到了的 Minecraft 服務器 EULA。
您的贡献请检查，否則我們將發送 DMCA 請求 Github 上。
感謝你的理解

**Comment by XCRailway** [comment]
Did I breaked the EULA of Minecraft?

**Comment by dmcacheckerforminecraft** [comment]
We will check it about 7 days later, thanks for you understanding.

**Comment by XCRailway** [comment]
你對你的 Minecraft 政策似乎违反到了的 Minecraft 服務器 EULA。
您的贡献请检查，否則我們將發送 DMCA 請求 Github 上。
感謝你的理解
OK =W=

**Comment by 0x4368697473756B6F** [comment]
hahahahaha

**Comment by komeiji-satori** [comment]
观光团

**Comment by KelaKim** [comment]
到此一游

**Comment by XCRailway** [comment]
然后我就去看mc的eula了

**Comment by 0x4368697473756B6F** [comment]
笑尿了

**Comment by dmcacheckerforminecraft** [comment]
Oh, we are sorry for our disturbing, we get a wrong report. Your repo is no problem.

**Comment by XCRailway** [comment]
Do you want to join our server?

**Comment by KelaKim** [comment]
hhhhhh还是不忘发广告

**Comment by XCRailway** [comment]
Reopen it!

**Comment by Frencis-fy** [comment]
interesting

**Comment by XCRailway** [comment]
@dmcacheckerforminecraft Let me send some ADs to you

**Comment by XCRailway** [comment]
Let me send some ADs

**Comment by dmcacheckerforminecraft** [comment]
Oh, We're happy to check if all players in your server have genuine license if you invite us to your server.

**Comment by fsgmhoward** [comment]
@dmcacheckerforminecraft You had better do that. I think 99% of his players' MC does not have genuine license. (May be a LITTLE bit lower than 99%?)

**Comment by dmcacheckerforminecraft** [comment]
We've heard there is VIPs in your server.
'let other people get access to anything we've made in a way that is unfair or unreasonable'
huh?

**Comment by XCRailway** [comment]
You can get VIP if you send our ADs to Youtube,Bilibili or other websites for 63 times

**Comment by XCRailway** [comment]
And you can get a spectial nikename in our QQ group and server.

**Comment by dmcacheckerforminecraft** [comment]
@fsgmhoward
This can't be the reason for breaking the law

**Comment by XCRailway** [comment]
Before 2016.7.19 We have VIP.But after 2016.7.19 VIP was be removed.

**Comment by JclMiku** [comment]
私にYouTubeのリンクを教えてください

**Comment by XCRailway** [comment]
Now,only my friends can have VIP

**Comment by dmcacheckerforminecraft** [comment]
@XCRailway Okay, that's sound great. A fair game environment can help the game develop.

**Comment by XCRailway** [comment]
@JclMiku sorry i don't understand Japanese. Please use chinese or english.

**Comment by XCRailway** [comment]
Our server have a very unfair texture packs.

**Comment by XCRailway** [comment]
Our server have a very unfair texture packs.

**Comment by JclMiku** [comment]
申し訳ありませんが、私は英語と中国語を話しません

**Comment by fsgmhoward** [comment]
@dmcacheckerforminecraft Nope, actually if you refer to his previous post:
> You can get VIP if you send our ADs to Youtube,Bilibili or other websites for 63 times

This is not considered fair right? I think that is a violation of MC EULA.

**Comment by XCRailway** [comment]
In that texture pack, All block's picture was be replaced to "XCRail server is good,Join our server now!*******"

**Comment by XCRailway** [comment]
@fsgmhoward Before 2016.7.19 We have VIP.But after 2016.7.19 VIP was be removed.Now,only my friends can have OP or other permissions.

**Comment by XCRailway** [comment]
In that texture pack, All sounds was be replaced to a voice "XCRail server is good,Join our server now!*******"

**Comment by KelaKim** [comment]
QQ register program need +86 mobile, but i have +1.

**Comment by XCRailway** [comment]
@KelaKim 

> QQ register program need +86 mobile, but i have +1.

You can use E-mail

**Comment by XCRailway** [comment]
@dmcacheckerforminecraft Why not join our server? XCRail is good,Fast join XC QQ Group!

**Comment by dmcacheckerforminecraft** [comment]
Um we are sorry, about texture, you mush let players have theirs right to change.
And the um... "texture" (actually we don't admire it IS a texture) in your server is terrible as out Committee thought. (We get many screenshots of it)

**Comment by fsgmhoward** [comment]
I am wondering currently how many people is watching this issue....

**Comment by Copay** [comment]
It's exciting i think.

**Comment by dmcacheckerforminecraft** [comment]
I mean "right to change", but you can still keep your right to recommend the server texture to players.

**Comment by XCRailway** [comment]
But the EULA saids "Otherwise we are quite relaxed about what you do - in fact we really encourage you to do cool stuff - but just don't do those things that we say you can't." That mean we can make our textures and mods freedomly.
We use some mods to make some cool stuff.If you disable texture,You will be jailed after 5 minute played.

**Comment by XCRailway** [comment]
You will be BANNED after 20 minute played.
IF YOU CHANGE THE RIGHT TEXTURE AFTER YOU BE BANNED,IT NEVER WORKING

**Comment by XCRailway** [comment]
YOU WILL BE BANNED FOREVER(But some OPs may unban you)

**Comment by XCRailway** [comment]
Because some mods,We must use texture packs.

**Comment by Frencis-fy** [comment]
mdzz

**Comment by dmcacheckerforminecraft** [comment]
Yeah, that's the problem, you can suggest them to use a texture(like Mojang designed it in Minecraft Server), but players SHOULD HAVE THEIRS RIGHTS to CHANGE the texture.

**Comment by XCRailway** [comment]
OK,I will change it in the next time.

**Comment by dmcacheckerforminecraft** [comment]
Thanks for your understanding.
We will re-open this issue if some one report this again and we confirm it.

**Comment by XCRailway** [comment]
Some player say to me "The texture is awful! It is full of the ADs ofthis server."

**Comment by XCRailway** [comment]
But I'm not usually go to github

**Comment by KelaKim** [comment]
But the texture you use may also be copyrighted

**Comment by XCRailway** [comment]
My client with our texture just played the AD songs.
I think,My player isn't like the AD songs.
Because it is very TERRIBLE.
The lyric is full of"XCRail is good,Fast join XC QQ Group!XCRail server never crash. xxxxxxxxxxx"

**Comment by fsgmhoward** [comment]
Siao liao this guy....

**Comment by XCRailway** [comment]
Because our texture, The player will be  brainwashed.
They will only can say"XCRail server is good"
They are be bored in that.

**Comment by XCRailway** [comment]
@dmcacheckerforminecraft Why not join our server? It's really cool!

**Comment by XCRailway** [comment]
小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284小曹铁路好，加群保平安，快进曹铁服务器，221312284

**Comment by XCRailway** [comment]
小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284小曹铁路好，加群保平安，快进小曹铁路曹铁服务器，221312284。XCrailway,Never Crash, fast join XCrailway server,Our QQ group is 221312284

**Comment by Copay** [comment]
What's fuck????????

**Comment by XCRailway** [comment]
I'll reopen it to send some ADs for my server

**Comment by XCRailway** [comment]
I will upload the texture.Please wait.You can download it and try to use it

**Comment by XCRailway** [comment]
@dmcacheckerforminecraft Are you still here?

**Comment by Frencis-fy** [comment]
@XCRailway Why are you still here to lost the Chinese people face.

**Comment by XCRailway** [comment]
Downloid it and unpack it to .minecraft/resourcepacks folder and start your Minecraft.I wish you can enjoy playing Minecraft with my texture.
But I'm sorry because you can't join my server.because you aren't chinese people.Most oversea player can't play in our server.Because it will usually timed out .Some oversea player can't connect our server.
@dmcacheckerforminecraft Thanks for you supporting me.

**Comment by Frencis-fy** [comment]
enjoy? Are you kidding me?

**Comment by XCRailway** [comment]
@Frencis-fy I will block you if you say our texture isn't good again.

**Comment by XCRailway** [comment]
![9 _qr tuke j 21i bfd](https://cloud.githubusercontent.com/assets/20753800/17329775/ab55b896-58f6-11e6-9374-dd26795558de.png)

**Comment by XCRailway** [comment]
That's very cool!

**Comment by XCRailway** [comment]
![b_rh_xyl0xymg__5jxgqzrf](https://cloud.githubusercontent.com/assets/20753800/17329920/50f64ce8-58f7-11e6-9323-fbbf7b5d7273.png)That's very very cool!

**Comment by komeiji-satori** [comment]
观光团

**Comment by laosb** [comment]
It's not good to have such Ads on GitHub.

在这里贴广告不合适。

**Comment by XCRailway** [comment]
@laosb 。。。。。。。

**Comment by XCRailway** [comment]
@laosb  OK I will don't have ads in next time.

**Comment by laosb** [comment]
I've reported abuse since you're not using this for actual developing. A hint by good: CC-BY licenses are not for code.

**Comment by sohaking** [comment]
i think he is just a primary school student...

**Comment by XCRailway** [comment]
@sohaking I‘m not.

**Comment by XCRailway** [comment]
I will look the conversation .If you need something please try to contact me in bilibili.
