### ISSUE TITLE
致 v2 观光团

### ISSUE THREAD

**Issue by gyn001** [XCRailway/XCRailAdvancedReplacer#3]
这是一个共享的账号。
这个账号不是小曹本人所控制的。
#1 的内容已经被小曹修改大半并锁定。

#1 是这个账号的其中一个控制者观看小曹的直播时创建的。
刚开始时是有恶作剧的心态，到后面开始为小曹提出友好的建议（不要用材质包赶走你的玩家）
这只是一个英语垃圾的无聊的人的恶作剧，诸位也请不要在意，谢谢。

各位 v2 众，最好不要以暴力手段攻击小曹，这样不太好，毕竟被他伤害的玩家都是自愿去玩的。

@XCRailway 不要修改这条信息（尽管你完全可以这么做），这是一条善意的劝告。
另外，如果想让大家真的认为小曹铁路好，请爱护你的玩家，而不是强迫你的玩家，更不要**批量的伤害其他群体**，他们都有各自喜爱的事物，不会容忍你不甚有诚意的行为。
爱玩家，爱非玩家。只有这样，你的小曹铁路才能活下来。

**Comment by XCRailway** [comment]
我是不会修改的

**Comment by gyn001** [comment]
@XCRailway 假的。
引用 v2 内容
> 看看一起能不能刷到 b 站最高在线人数

**Comment by XCRailway** [comment]
@gyn001 知道了 我已经上首页了

**Comment by sohaking** [comment]
什么时候从小学毕业了就会好很多了。

**Comment by Frencis-fy** [comment]
+1s

**Comment by sohaking** [comment]
可以的，一言不合删comment。这种做法……这是我在这个issue的最后一个回复。dalao们长者们都是希望你能够从小学毕业才来关注你的。
